### ISSUE TITLE
Help: program exits abnormally with `exit status 0xc0000005` 

### ISSUE THREAD

**Issue by anhoder** [saltosystems/winrt-go#94]
After registering an event callback, the program may exit unexpectedly when the event is triggered, and left only `exit status 0xc0000005`

![image](https://github.com/saltosystems/winrt-go/assets/27605589/6d481816-8bec-40cf-adcc-e009b577cd63)

This is a demo that can be reproduced, it is a simple program based on [bubbletea](https://github.com/charmbracelet/bubbletea)(sorry, I can't reproduce on other simpler demos).

```go
package main

import (
	"fmt"
	"log"
	"path/filepath"
	"runtime"
	"time"
	"unsafe"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go"
	"github.com/saltosystems/winrt-go/windows/foundation"
	"github.com/saltosystems/winrt-go/windows/media/core"
	"github.com/saltosystems/winrt-go/windows/media/playback"
)

func main() {
	p := tea.NewProgram(newModel(), tea.WithAltScreen())
	if _, err := p.Run(); err != nil {
		log.Fatal(err)
	}
}

type model struct {
	player *playback.MediaPlayer
	t      time.Duration
}

func newModel() *model {
	_ = ole.RoInitialize(1)

	// NOTE: init player
	p, _ := playback.NewMediaPlayer()
	playbackSession, _ := p.GetPlaybackSession()
	_ = p.SetAudioCategory(playback.MediaPlayerAudioCategoryMedia)

	// NOTE: register callback
	eventReceivedGuid := winrt.ParameterizedInstanceGUID(
		foundation.GUIDTypedEventHandler,
		playback.SignatureMediaPlaybackSession,
		"cinterface(IInspectable)",
	)
	h := foundation.NewTypedEventHandler(ole.NewGUID(eventReceivedGuid), func(_ *foundation.TypedEventHandler, sender, _ unsafe.Pointer) {})
	_, _ = playbackSession.AddPlaybackStateChanged(h)

	return &model{player: p}
}

func (m model) Init() tea.Cmd {
	return tick()
}

func (m model) Update(message tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := message.(type) {
	case tea.KeyMsg:
		key := msg.String()
		switch key {
		case "q", "esc", "ctrl+c":
			return m, tea.Quit
		case " ":
			// NOTE: run gc
			runtime.GC()

			// NOTE: start play, will trigger callback event
			m.play()
			return m, tick()
		}

	case tickMsg:
		m.t += time.Millisecond * 100
		return m, tick()
	}

	return m, nil
}

func (m model) View() string {
	return fmt.Sprintf("\n\n     Hello world! %s", m.t)
}

func (m model) play() {
	_, path, _, _ := runtime.Caller(0)
	uri, _ := foundation.UriCreateUri("file:///" + filepath.Dir(path) + "/a.mp3")
	s, _ := core.MediaSourceCreateFromUri(uri)
	_ = m.player.SetSource((*playback.IMediaPlaybackSource)(unsafe.Pointer(s)))
	_ = m.player.Play()
}

type tickMsg time.Time

func tick() tea.Cmd {
	return tea.Tick(time.Millisecond*100, func(t time.Time) tea.Msg {
		return tickMsg(t)
	})
}
```
[demo.zip](https://github.com/saltosystems/winrt-go/files/15251418/demo.zip)

After the program is running, click the space key several times, and it may exit abnormally

I guess it's a memory issue caused by go gc

When I disabled the gc with `debug.SetGCPercent(-1)`, it worked fine

It's been bothering me for a few days, have you encountered this problem? 😢

**Comment by jagobagascon** [comment]
Hi! Thanks for the code sample, I can effectively reproduce the issue now.

The error occurs when we pass a Go pointer to WinRT, and the pointer is moved or deleted by the GC. The go runtime usually throws an error if it finds out. But for some reason it is not detecting it.

After lot's of testing I found the culprit:
https://github.com/saltosystems/winrt-go/blob/45c2d7a6235a343dda6c6538ae78bd4b6d329f33/windows/foundation/typedeventhandler.go#L53

We fixed a simmilar issue in the past (#64), and I can't believe how I missed such an obvious mistake 😅.

After fixing that the issue does no longer happen to me. Could you test the branch I pushed to #95 and see if it's fixed now?

**Comment by anhoder** [comment]
Nice! Thanks for your work! 

I tried again with the new branch and it worked great.
Thanks again for the fix.

**Comment by balazsgrill** [comment]
I encountered a similar issue with a very simple test:

https://github.com/balazsgrill/winrt-go/blob/main/storage_test.go

However I doubt that this time it would be caused by the GC as it still fails when I disable it

```
Exception 0xc0000005 0x1 0x50 0x7ffa3fa96d43
PC=0x7ffa3fa96d43
```
